### ISSUE TITLE
Extract Error 

### ISSUE THREAD

**Issue by iskycc** [ntkme/feedbin#20]
After I set it up, no article can be extracted.

 (When I click on the 'extract' button, it immediately shows "Unable to extract this article's content.")

Are you all right? How should I check for errors?

Thanks.

**Comment by ntkme** [comment]
I cannot reproduce your issue. Extract works fine for me, so that it might be a specific issue to the feed(s) you're trying to extract.

First step of debugging a web service is always checking the browser inspector and see if there is any details you can get from the console log or request/response payload from network tab. 

To check for server side issues, first get into the shell of the parent container, and run `podman ps` to see the status all child containers. There should be 12 containers running after the service is fully up:

```
$ docker exec -it feedbin /bin/bash
bash-5.1# podman ps
CONTAINER ID  IMAGE                                       COMMAND               CREATED             STATUS                 PORTS       NAMES
962f3ac86cca  docker.io/library/redis:6-alpine            redis-server --ap...  About a minute ago  Up About a minute ago              redis
3de074b26e19  docker.io/library/postgres:14-alpine        postgres              About a minute ago  Up About a minute ago              postgres
127a69a9cf4e  docker.io/library/elasticsearch:2.4-alpine  elasticsearch         About a minute ago  Up About a minute ago              elasticsearch
61c8f065adc4  docker.io/library/memcached:1-alpine        memcached             About a minute ago  Up About a minute ago              memcached
2b051846bd67  docker.io/library/caddy:2-alpine            caddy run --confi...  About a minute ago  Up About a minute ago              caddy
e20b76ae2ace  docker.io/minio/minio:latest                server /data          About a minute ago  Up About a minute ago              minio
1245052c4b51  localhost/feedbin:edge                      sh -c if test -n ...  About a minute ago  Up About a minute ago              feedbin-extract
c24db25faaf5  localhost/feedbin:edge                      node server.js        About a minute ago  Up About a minute ago              camo
7925f4e94cc0  localhost/feedbin:edge                      bundle exec forem...  About a minute ago  Up About a minute ago              feedbin-image
25567eee463f  localhost/feedbin:edge                      bundle exec forem...  About a minute ago  Up About a minute ago              feedbin-refresher
d9c5c7227aa5  localhost/feedbin:edge                      bundle exec forem...  About a minute ago  Up About a minute ago              feedbin
3885df5980db  localhost/feedbin:edge                      /bin/sh -c bundle...  About a minute ago  Up About a minute ago              feedbin-rails
```

If some container(s) did not come up, run `systemctl list-units --failed` to list the failed systemd units, and then use `journalctl -u ${failed_service_name}` to check the log of failed service.

Then, the next step of debugging would be checking the console log for a running container. For example:

```
bash-5.1# podman logs feedbin-extract
```

Note: `feedbin-extract` usually does not log anything unless something goes wrong.

Again, I cannot reproduce your issue. You should try the steps above and see if you can find out any clue.

**Comment by iskycc** [comment]
Ok,....I reset my server and re-installed it, and there are no problems anymore. thank you.
